/* eslint-disable */
// Generated by Wrangler by running `wrangler types counter/worker-configuration.d.ts --config counter/wrangler.jsonc --include-runtime false` (hash: 304f4a86b1149300f416835eb8c7fc69)
interface __BaseEnv_Env {
	DB: D1Database;
	SPIN_RATE_LIMITER: RateLimit;
	ACCOUNT_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGIN: "https://nagisanzenin.github.io";
	GOOGLE_CLIENT_ID: "695244761055-bqfhbgjv4o5nephk5urbu33f8j1gr4a1.apps.googleusercontent.com";
	ADMIN_GOOGLE_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "GOOGLE_CLIENT_ID" | "ADMIN_GOOGLE_EMAIL">> {}
}
